version: '3.7'

services:
  no-health-checking:
    image: no-health-checking
    healthcheck:
      test: ["CMD", "/checking.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s